### PR TITLE
Fixing broken for puppet-lint >= 2.4.0

### PR DESCRIPTION
**Pull request by baurmatt**
This is an empty PR to let Travis run and show the problem.

As a small example:

```bash
$ bundle exec rspec ./spec/puppet-lint/plugins/legacy_facts_spec.rb:267
Run options: include {:locations=>{"./spec/puppet-lint/plugins/legacy_facts_spec.rb"=>[267]}}

legacy_facts
  with fix enabled
    fact variable using legacy $::sshrsakey
      should use the facts hash (FAILED - 1)

Failures:

  1) legacy_facts with fix enabled fact variable using legacy $::sshrsakey should use the facts hash
     Failure/Error: expect(manifest).to eq("$facts['ssh']['rsa']['key']")

       expected: "$facts['ssh']['rsa']['key']"
            got: "$::sshrsakey"

       (compared using ==)
     # ./spec/puppet-lint/plugins/legacy_facts_spec.rb:268:in `block (4 levels) in <top (required)>'

Finished in 0.00994 seconds (files took 0.19942 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/puppet-lint/plugins/legacy_facts_spec.rb:267 # legacy_facts with fix enabled fact variable using legacy $::sshrsakey should use the facts hash

Coverage report generated for RSpec to /Users/mbaur/Sources/puppet-lint-legacy_facts-check/coverage. 0.0 / 0.0 LOC (100.0%) covered.
```

A lot of the "fixes" don't work anymore. My tests show that this starts to happen with puppet-lint 2.4.0.

Problem seems to be here:

https://github.com/mmckinst/puppet-lint-legacy_facts-check/blob/0741bbf0856aa515e54e21279895f6c981a35884/lib/puppet-lint/plugins/legacy_facts.rb#L128

It gets triggered because `problem[:token].value != problem[:token].raw` and therefore no fixing is attempted for this line.

To be honest, I don't really get why this line was introduced in the first place. Perhaps @seanmil has some deeper insight why this started to break in 2.4.0? He introduce this change in #13.

### CODE REVIEW

**Comment by baurmatt** [comment]
[Failing test](https://travis-ci.org/mmckinst/puppet-lint-legacy_facts-check/builds/633303730)

**Comment by mmckinst** [comment]
Thanks for bringing this to my attention. I've found forcing it to use puppet-lint 2.3.6 at https://github.com/mmckinst/puppet-lint-legacy_facts-check/pull/29 seems to fix it for everything except ruby 1.9.3 as you can see at https://travis-ci.org/mmckinst/puppet-lint-legacy_facts-check/builds/635072450 .

I'll take a deeper look at this later and see what has changed between puppet-lint 2.3.6 and puppet-lint 2.4.0.

**Comment by mmckinst** [comment]
ref https://github.com/rodjek/puppet-lint/issues/902

**Comment by baurmatt** [comment]
Ha awesome, looks like Alex stumbled over this as well :) Looking forward to a fix! If I can help somehow, please let me know! :)

**Comment by mmckinst** [comment]
1.0.3 has been released which works around this problem. TBD what the long term fix is so this can go back on puppet-lint 2.4.0.

**Comment by baurmatt** [comment]
Thank you! :)

**Comment by mmckinst** [comment]
This was fixed in https://github.com/mmckinst/puppet-lint-legacy_facts-check/pull/32 . 

Thanks for submitting the bug report.

**Pull request closed without merging**
